name: Playlist automation CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Set up Node.js env
      uses: actions/setup-node@v4
      with:
        node-version: '24' # Specify your Node version here
        cache: 'npm'       # Caches npm dependencies for faster runs

    - name: Install dependencies
      run: npm ci          # "Clean Install" - best for automated CI pipelines

    - name: Run validation or tests
      run: npm test        # Make sure you have a "test" script defined in package.json
      
    
    
  deploy:
    needs: build-and-test
    runs-on: self-hosted
    steps:
    - name: Run Deploy Script via Native SSH
      env:
        # Pulling your repository secrets into the environment variables
        SSH_KEY: ${{ secrets.SSH_KEY }}
        SSH_HOST: ${{ secrets.SERVER_HOST }}
      run: echo "$SSH_KEY" > ~/.ssh/id_priv && ssh -o StrictHostKeyChecking=no testuser@"178.104.90.70" "sh /mnt/HC_Volume_105180630/deployed/run.sh"
